### ISSUE TITLE
Label Generator/NaN Loss?

### ISSUE THREAD

**Issue by clu5** [yashk2810/Semantic-Image-Segmentation#1]
What should the shape be of output for the generators? The images I get are shape of (468, 360, 480, 3) but the label_int are shape(468, 360, 480). 

Also did your training ever start with NaN loss?

**Comment by yashk2810** [comment]
If you are following Jeremy's code, he used a different dataset. What I am using is different. For your training try using tanh as the activation function, your gradients are exploding

**Comment by clu5** [comment]
Thanks, Jeremy had a different number of classes when creating the model and caused the nan loss.

Do you know how to change the generators/model for a different dataset with binary classes?

**Comment by yashk2810** [comment]
I would have to try if it is being used on a binary classification.
