### ISSUE TITLE
where is the data

### ISSUE THREAD

**Issue by akshaylamba** [yashk2810/Semantic-Image-Segmentation#2]
Hello 

PLs Let me know about the location of data and labels...

**Comment by yashk2810** [comment]
The data can be found at https://github.com/mostafaizz/camvid. You can clone this repository.

**Comment by akshaylamba** [comment]
![0016e5_08027_l](https://user-images.githubusercontent.com/19161823/27598071-fb04a602-5b81-11e7-9acd-bf0be10cd71d.jpeg)


Which Software is used to create the labels as shown Above...

Pls suggest.I need to Make labels for my own data set..

**Comment by yashk2810** [comment]
I don't know how the labels were created. I have just downloaded the dataset.
